
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { LanguageProvider } from "@/contexts/LanguageContext";
import DynamicLayout from "@/components/DynamicLayout";
import ResponsiveLayout from "@/components/ResponsiveLayout";
import SWRProvider from "@/providers/SWRProvider";
import ReduxProvider from "@/redux/ReduxProvider";
import AuthProvider from "@/providers/AuthProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
// import { Inter } from 'next/font/google';
// import { Noto_Sans_Arabic } from 'next/font/google';

// Configure fonts with better error handling
// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-inter',
// });

// const notoSansArabic = Noto_Sans_Arabic({
//   subsets: ['arabic'],
//   display: 'swap',
//   variable: '--font-noto-arabic',
// });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  
  return (
    <html 
    // className={`${inter.variable} ${notoSansArabic.variable}`}
    >
      <body
        className="font-system-arabic antialiased"
      >
        <LanguageProvider>
          <ThemeProvider>
            <SWRProvider>
              <ReduxProvider>
                <AuthProvider>
                  <DynamicLayout>
                    <ResponsiveLayout>
                      {children}
                    </ResponsiveLayout>
                  </DynamicLayout>
                </AuthProvider>
                <ToastContainer
                  position="top-right"
                  autoClose={3000}
                  hideProgressBar={false}
                  newestOnTop={false}
                  closeOnClick
                  rtl={true}
                  pauseOnFocusLoss
                  draggable
                  pauseOnHover
                  theme="colored"
                />
              </ReduxProvider>
            </SWRProvider>
          </ThemeProvider>
        </LanguageProvider>
   
      </body>
    </html>
  );
}
